### ISSUE TITLE
core dump when run demo.py

### ISSUE THREAD

**Issue by xiebinghua** [facebookresearch/vggsfm#16]
![image](https://github.com/facebookresearch/vggsfm/assets/40881816/a6a40495-5845-4bbf-96c7-b37c289ddcf0)
python demo.py SCENE_DIR=examples/cake resume_ckpt=./vggsfm_v2_0_0.bin

**Comment by xiebinghua** [comment]
![image](https://github.com/facebookresearch/vggsfm/assets/40881816/e0344e2f-7e39-493c-853b-1589a4401007)
maybe becase of importing the vggsfm above

**Comment by xiebinghua** [comment]
![image](https://github.com/facebookresearch/vggsfm/assets/40881816/8c1efe9c-20d3-4d39-9283-87c5255d7c11)
![image](https://github.com/facebookresearch/vggsfm/assets/40881816/844cf994-ab02-4f51-b98e-66603bfa18b0)

**Comment by jytime** [comment]
Hi @xiebinghua ,

Could you please open a terminal and run the following command step by step?


```
python
from pytorch3d.renderer.cameras import CamerasBase, PerspectiveCameras

from vggsfm.datasets.demo_loader import DemoLoader
from vggsfm.two_view_geo.estimate_preliminary import estimate_preliminary_cameras

```
It will help identify which command is the root

**Comment by xiebinghua** [comment]
@jytime thanks，something wrong happens when I create conda environment,  and now I finish the conda env creation, and I can run demo well. But when I run apple case, cuda memory consume is too large, I want to know how to decrease the cuda momery through yaml config? hope for your reply.  Another thing is that we hope you provide a docker file to create environment more easily.

**Comment by 1511607288** [comment]
Hi,i do have the same problem when running demo.py, but i am not sure that is problem of  conda env creation. I created the env by running "source install.sh". What should i be aware of when creating conda env? Thank you for your help!

**Comment by 1511607288** [comment]
> Hi @xiebinghua ,
> 
> Could you please open a terminal and run the following command step by step?
> 
> ```
> python
> from pytorch3d.renderer.cameras import CamerasBase, PerspectiveCameras
> 
> from vggsfm.datasets.demo_loader import DemoLoader
> from vggsfm.two_view_geo.estimate_preliminary import estimate_preliminary_cameras
> ```
> 
> It will help identify which command is the root

And I do as you asked, it seems the last command's problem, but how can i fix this? Thank you for your help!
![非法指令](https://github.com/facebookresearch/vggsfm/assets/53338107/ccac7833-e915-4311-9e10-e35898992abd)

**Comment by xiebinghua** [comment]
@1511607288 sorry，I don't know clearly how to fix this core dump. I just install the necessary python package in install.sh in my other conda environment and everything is ok.

**Comment by jytime** [comment]
Hi @1511607288,

It seems poselib is not installed correctly. Can you try if you can ``` import poselib``` successfully?

If not, you can also run ```pip instal https://huggingface.co/facebook/VGGSfM/resolve/main/poselib-2.0.2-cp310-cp310-linux_x86_64.whl``` to install poselib specially.

**Comment by jytime** [comment]
Hi @xiebinghua ,
1. Please try ```max_query_pts=1024``` for the apple scene.
2. We are not allowed to use docker in our cluster. But I will provide a hugging face demo then.

**Comment by jytime** [comment]
We have released a hugging face demo at https://huggingface.co/spaces/facebook/vggsfm

**Comment by polar-explorer** [comment]
Hi, I also have this problem here:
`python
from vggsfm.two_view_geo.estimate_preliminary import estimate_preliminary_cameras`
Although I installed the poselib specially, this problem has not been solved and I still can't ` import poselib` successfully

**Comment by jytime** [comment]
If so, can you just try:

```
pip install poselib==2.0.2
```

**Comment by polar-explorer** [comment]
Hi @jytime 
Thank you for your reply. It seems that I have already intalled posedlib, but it still does not work, as shown below:
![Screenshot from 2024-07-10 08-33-11](https://github.com/facebookresearch/vggsfm/assets/80018873/d4978812-3d90-4785-83d8-a2fe8dafbfb1)
This core dumped shows even without poselib at `from vggsfm.two_view_geo.estimate_preliminary import estimate_preliminary_cameras`.

**Comment by jytime** [comment]
Hi @polar-explorer ,

sry I should make it clearer. Please first uninstall the wrong version, and try to reinstall again:

```
pip uninstall poselib
pip install poselib==2.0.2
```

**Comment by polar-explorer** [comment]
Hi @jytime,
Thanks a lot for your help! Everything's working now.
